check challenge yaml file before loading it
deadlock-resources/dcli pull request #2
Opened 2020-04-14 15:54 UTC by chetana

2020-04-15 09:58 UTC, Slayug commented
Thanks for the PR  
you could do something with less duplicate code, create a generic method, and call it each time it's necessary.

2020-04-15 12:32 UTC, any-lia requested changes
Thanks for the PR
you could do something with less duplicate code, create a generic method, and call it each time it's necessary.

2020-04-16 11:42 UTC, any-lia requested changes

2020-04-16 11:42 UTC, Slayug commented on dcli/runner.py
> +def checkYamlFile(path):
Your method is doing more than only 'check the yaml file', find a better function name, yesterday I refactored the code to be compliant with python function naming rule. Method must be that way: check_smth. Don't forget to rebase.

2020-04-16 15:22 UTC, merged