chore: refacto language generation for dcli
deadlock-resources/dcli pull request #6
Opened 2020-05-14 15:59 UTC by acktnow

2020-05-18 09:33 UTC, any-lia requested changes
C'est possible de gérer le cas où qqu met un language non connu ?
exemple :

```bash
 /tmp  dcli gen to
Traceback (most recent call last):
  File "/home/bug/.local/bin/dcli", line 6, in <module>
    cli.main()
  File "/home/bug/.local/lib/python3.8/site-packages/dcli/cli.py", line 26, in main
    fire.Fire({
  File "/home/bug/.local/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bug/.local/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/bug/.local/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/bug/.local/lib/python3.8/site-packages/dcli/cli.py", line 23, in gen_with_type
    generate_for_language(l)
  File "/home/bug/.local/lib/python3.8/site-packages/dcli/generatorCli.py", line 85, in generate_for_language
    language = LANGUAGES[langId]
KeyError: 'to'
```


Good job sinon :)

2020-05-18 09:33 UTC, Slayug commented on dcli/language/c/__init__.py
> +
Pour ce language tu n'as pas implémenté la méthod `need_to_generate_new_type` donc il y a une classe générée pour chaque type, même les primitifs.

2020-05-18 09:33 UTC, Slayug commented on dcli/language/c/__init__.py
> +
De même en cpp

2020-05-19 13:23 UTC, acktnow commented on dcli/language/c/__init__.py
> +
Done

2020-05-28 12:07 UTC, merged